Spring:
  datasource:
    url: jdbc:mysql://:3306/ActivityManger
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  mail:
    host: smtp.163.com
    username: 
    password: 

  data:
    redis:
      host: 
      port: 
      password: 
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8


server:
  port: 18088

mybatis:
  #mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.activity_manage.Entity
  configuration:
    map-underscore-to-camel-case: true
